
title: Joel Schwartz
email: contact@joel-schartz.com
description: author / playwright
baseurl: ""
url: ""

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

show_downloads: false

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
