
title: Joel Schwartz
email: contact@joel-schartz.com
description: author / playwright
baseurl: ""
url: "https://joel-schwartz.com"

theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

collections:
  page-list:
    output: true

google_analytics: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/